broj_a = float(input("Upisite prvi broj: "))
broj_b = float(input("Upisite drugi broj: "))
print("Brojevi su: {}, {}".format(broj_a,broj_b))
print("{} + {} = {}".format(broj_a,broj_b,broj_a+broj_b))
print("{} - {} = {}".format(broj_a,broj_b,broj_a-broj_b))
print("{} * {} = {}".format(broj_a,broj_b,broj_a*broj_b))
print("{} / {} = {}".format(broj_a,broj_b,broj_a/broj_b))
print("{} // {} = {}".format(broj_a,broj_b,broj_a//broj_b))
print("{} ^ {} = {}".format(broj_a,broj_b,pow(broj_a,broj_b)))
print("{} % {} = {}".format(broj_a,broj_b,broj_a%broj_b))
print("{} % {} = {}".format(broj_a,broj_b,broj_a%broj_b))